atec: &DEFAULT
  batch_size: 128
  hidden_size: 200
  num_layers: 2
  num_epoch: 50
  learning_rate: 1.0e-3
  decay_rate: 0.95
  decay_steps: 1000
  keep_prop: 0.8
  num_classes: 2
  grad_max: 6
  max_len: 50
  embed_size: 300
  scale_l2: 0
  label_smoothing: 0.1
  earlystop_patience: 5

quora:
  <<: *DEFAULT
  decay_steps: 2500